In [1]:
import pandas as pd
import numpy as np

In [2]:
load=pd.read_csv('pre_placement.csv')

In [3]:
from sklearn.feature_selection import SelectKBest,chi2,RFE

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
load.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [6]:
load=pd.get_dummies(load,drop_first=True).astype(int)

In [7]:
load.tail()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender_M,ssc_b_Others,hsc_b_Others,hsc_s_Commerce,hsc_s_Science,degree_t_Others,degree_t_Sci&Tech,workex_Yes,specialisation_Mkt&HR,status_Placed
210,211,80,82,77,91,74,400000,1,1,1,1,0,0,0,0,0,1
211,212,58,60,72,74,53,275000,1,1,1,0,1,0,1,0,0,1
212,213,67,67,73,59,69,295000,1,1,1,1,0,0,0,1,0,1
213,214,74,66,58,70,60,204000,0,1,1,1,0,0,0,0,1,1
214,215,62,58,53,89,60,0,1,0,1,0,1,0,0,0,1,0

In [8]:
x=load.drop('salary',axis=1)
y=load['salary']

In [9]:
kbest=SelectKBest(score_func=chi2,k=7)
fits=kbest.fit(x,y)
x=fits.transform(x)

In [19]:
kbest.scores_

array([1401.11231391,  207.90637101,  155.37038383,   74.02250599,
        146.02654512,   39.0244544 ,   16.98818224,   24.75184487,
         17.33101519,   22.62767947,   26.41313656,   15.80965695,
         32.6728822 ,   37.83013722,   25.82847241,   67.        ])

In [21]:
kbest.get_support()

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False,  True])

In [10]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
dt=LinearRegression()
dt.fit(xtrain,ytrain)

LinearRegression()

In [12]:
ypred=dt.predict(xtest)

In [13]:
from sklearn.metrics import r2_score
r2=r2_score(ytest,ypred)

In [14]:
r2

0.7353130343516066

In [33]:
model_score=[]
model_score.append(r2)

In [34]:
df=pd.DataFrame(index=['r2'],columns=['multi linear regression'])

In [35]:
df

   multi linear regression
r2                     NaN

In [38]:
df.iloc[0,0]=model_score[0]

In [39]:
df

   multi linear regression
r2                0.735313