## import all lib for our project:

In [38]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [40]:
from sklearn.feature_selection import SelectKBest,chi2

In [65]:
def feature_selections(x,y,k):
    kb=SelectKBest(score_func=chi2,k=k)
    fit_feature=kb.fit(x,y)
    features=fit_feature.transform(x)
    return features

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
def split_scaler(x,y):
    xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.24,random_state=42)
    sc=StandardScaler()
    xtrain=sc.fit_transform(xtrain)
    xtest=sc.transform(xtest)
    return xtrain,xtest,ytrain,ytest

In [45]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [46]:
from sklearn.metrics import accuracy_score

In [81]:
def accuracy(model,xtest,ytest):
    pred=model.predict(xtest)
    acc=accuracy_score(ytest,pred)
    return round(acc,2)

In [49]:
# model fit:
knn=KNeighborsClassifier()
svc=SVC()
nb=GaussianNB()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()

In [50]:
model_list=[knn,svc,nb,dt,rf]

In [83]:
scores

[0.94, 0.93, 0.85, 0.95, 0.97]

In [79]:
# Accuracy=[round(x,2) for x in scores]

In [84]:
# Accuracy

## data load and score calculation:

In [52]:
load=pd.read_csv('clean_CKD.csv')

In [54]:
load=load.drop('id',axis=1)

In [56]:
load.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

### remove space in dataset:

In [58]:
load=load.apply(
    lambda col:col.str.strip() if col.dtype=='object' else col
)

In [59]:
load['classification'].unique()

array(['ckd', 'notckd'], dtype=object)

In [60]:
load.head()

    age    bp     sg   al   su     rbc        pc         pcc  ...    rc  htn   dm  cad  appet   pe  ane  classification
0  48.0  80.0  1.020  1.0  0.0  normal    normal  notpresent  ...  5.20  yes  yes   no   good   no   no             ckd
1   7.0  50.0  1.020  4.0  0.0  normal    normal  notpresent  ...  5.48   no   no   no   good   no   no             ckd
2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  ...  4.46   no  yes   no   poor   no  yes             ckd
3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  ...  3.90  yes   no   no   poor  yes  yes             ckd
4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  ...  4.60   no   no   no   good   no   no             ckd

[5 rows x 25 columns]

In [61]:
load=pd.get_dummies(load,drop_first=True).astype(int)

In [62]:
load.head()

   age  bp  sg  al  su  bgr  bu  ...  htn_yes  dm_yes  cad_yes  appet_poor  pe_yes  ane_yes  classification_notckd
0   48  80   1   1   0  121  36  ...        1       1        0           0       0        0                      0
1    7  50   1   4   0  121  18  ...        0       0        0           0       0        0                      0
2   62  80   1   2   3  423  53  ...        0       1        0           1       0        1                      0
3   48  70   1   4   0  117  56  ...        1       0        0           1       1        1                      0
4   51  80   1   2   0  106  26  ...        0       0        0           0       0        0                      0

[5 rows x 25 columns]

## Execution part :

In [120]:
x=load.drop('classification_notckd',axis=1)
y=load['classification_notckd']

In [121]:
x=feature_selections(x,y,10)

@ train & test splitscaler:

In [122]:
xtrain,xtest,ytrain,ytest=split_scaler(x,y)

In [123]:
scores=[]
for i in model_list:
    model_fit=i.fit(xtrain,ytrain)
    accs=accuracy(model_fit,xtest,ytest)
    scores.append(accs)

In [124]:
scores

[0.98, 1.0, 0.93, 0.97, 1.0]

## create dataframe:

In [104]:
dataframe=pd.DataFrame(index=['CHI2'],columns=['KNN','SVC','NB','DT','RF'])

In [ ]:
cols=['KNN','SVC','NB','DT','RF']
for value in scores:
    dataframe[]

In [105]:
dataframe

      KNN  SVC   NB   DT   RF
CHI2  NaN  NaN  NaN  NaN  NaN

In [107]:
cols=['KNN','SVC','NB','DT','RF']

In [125]:
num=0
for i  in cols:
    dataframe[i][0]=scores[num]
    num+=1

C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe[i][0]=scores[num]
C:\Users\Smile\AppData\Local\Temp\ipykernel_7520\744231298.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  dataframe[i][0]=scores[num]

In [126]:
dataframe

       KNN  SVC    NB    DT   RF
CHI2  0.98  1.0  0.93  0.97  1.0

In [ ]:
# svc and rf I think overfitting....